### ISSUE TITLE
Part 1c, broken external link

### ISSUE THREAD

**Issue by cuprousoxide** [fullstackopen-2019/fullstackopen-2019.github.io#212]
The link titled 'currying,' redirecting to the following page is broken:
http://www.datchley.name/currying-vs-partial-application/

Not sure if it's temporary, but the entire datchley.name site appears to be down

**Comment by marklaatikainen** [comment]
@mluukkai

**Comment by JuhQ** [comment]
If all else fails, we could use web archive link http://web.archive.org/web/20190607091631/http://www.datchley.name/currying-vs-partial-application/

**Comment by lobzison** [comment]
I'm not an FP expert by any means, but it seems that currying is wrong term to use for the given example.

From the article above:
> Currying is the process of taking a function that accepts N arguments and turning it into a chained series of N functions each taking 1 argument.

And example that we have is turning 
`const setToValue = (value) => setCounter(value)`
into
`const setToValue = (value) => () => setCounter(value)`

So we have a `A => B` that we are turning into `A => () => B`
So it's not the currying from the definition with is `(A, B) => C` turning into `A => B => C`

I think the better concept would be "function that return a thunk". Since thunks are used extensively so far, and fairly easy to understand - it would be better.

Anyway - enjoying the course so far, thanks for it.

**Comment by marklaatikainen** [comment]
Link fixed in  #314
