### ISSUE TITLE
Explain about no need closing DB connection in part 3c

### ISSUE THREAD

**Issue by andrejkurusiov** [fullstackopen-2019/fullstackopen-2019.github.io#522]
After the part

> The public interface of the module is defined by setting a value to the _module.exports_ variable. We will set the value to be the <i>Note</i> model. The other things defined inside of the module, like the variables _mongoose_ and _url_ will not be accessible or visible to users of the module.

there's no explicit closure of DB connection.

Please explain why there's no `mongoose.connection.close()` any more although it's specifically highlighted that it _should_ be done.

**Comment by mluukkai** [comment]
Your right, this needs clarification.

The reason is that web server remains all the time running, and it keeps reusing the same connection for all requests.

In command line script similar reuse of the connection is not possible if the program does just one or few queries. If the connection is not explicitly closed, the program does not end properly and keeps on hanging forever or until Control+C, or something causes it to stop
